// Datos geográficos de Argentina: provincias y municipios/partidos.
// Fuente: nomenclatura oficial del INDEC / datos.gob.ar
// Buenos Aires incluye los 135 partidos completos.
// Resto de provincias incluye municipios principales.

export type Provincia = {
  id: string;
  nombre: string;
};

export type Municipio = {
  nombre: string;
  provinciaId: string;
};

export const PROVINCIAS: Provincia[] = [
  { id: "caba", nombre: "Ciudad Autónoma de Buenos Aires" },
  { id: "buenos-aires", nombre: "Buenos Aires" },
  { id: "catamarca", nombre: "Catamarca" },
  { id: "chaco", nombre: "Chaco" },
  { id: "chubut", nombre: "Chubut" },
  { id: "cordoba", nombre: "Córdoba" },
  { id: "corrientes", nombre: "Corrientes" },
  { id: "entre-rios", nombre: "Entre Ríos" },
  { id: "formosa", nombre: "Formosa" },
  { id: "jujuy", nombre: "Jujuy" },
  { id: "la-pampa", nombre: "La Pampa" },
  { id: "la-rioja", nombre: "La Rioja" },
  { id: "mendoza", nombre: "Mendoza" },
  { id: "misiones", nombre: "Misiones" },
  { id: "neuquen", nombre: "Neuquén" },
  { id: "rio-negro", nombre: "Río Negro" },
  { id: "salta", nombre: "Salta" },
  { id: "san-juan", nombre: "San Juan" },
  { id: "san-luis", nombre: "San Luis" },
  { id: "santa-cruz", nombre: "Santa Cruz" },
  { id: "santa-fe", nombre: "Santa Fe" },
  { id: "santiago-del-estero", nombre: "Santiago del Estero" },
  { id: "tierra-del-fuego", nombre: "Tierra del Fuego" },
  { id: "tucuman", nombre: "Tucumán" },
];

export const MUNICIPIOS: Municipio[] = [
  // ─── Ciudad Autónoma de Buenos Aires ───
  { nombre: "Ciudad Autónoma de Buenos Aires", provinciaId: "caba" },

  // ─── Buenos Aires — 135 partidos ───
  { nombre: "Adolfo Alsina", provinciaId: "buenos-aires" },
  { nombre: "Adolfo Gonzales Chaves", provinciaId: "buenos-aires" },
  { nombre: "Alberti", provinciaId: "buenos-aires" },
  { nombre: "Almirante Brown", provinciaId: "buenos-aires" },
  { nombre: "Arrecifes", provinciaId: "buenos-aires" },
  { nombre: "Avellaneda", provinciaId: "buenos-aires" },
  { nombre: "Ayacucho", provinciaId: "buenos-aires" },
  { nombre: "Azul", provinciaId: "buenos-aires" },
  { nombre: "Bahía Blanca", provinciaId: "buenos-aires" },
  { nombre: "Balcarce", provinciaId: "buenos-aires" },
  { nombre: "Baradero", provinciaId: "buenos-aires" },
  { nombre: "Benito Juárez", provinciaId: "buenos-aires" },
  { nombre: "Berazategui", provinciaId: "buenos-aires" },
  { nombre: "Berisso", provinciaId: "buenos-aires" },
  { nombre: "Bolívar", provinciaId: "buenos-aires" },
  { nombre: "Bragado", provinciaId: "buenos-aires" },
  { nombre: "Brandsen", provinciaId: "buenos-aires" },
  { nombre: "Campana", provinciaId: "buenos-aires" },
  { nombre: "Cañuelas", provinciaId: "buenos-aires" },
  { nombre: "Capitán Sarmiento", provinciaId: "buenos-aires" },
  { nombre: "Carlos Casares", provinciaId: "buenos-aires" },
  { nombre: "Carlos Tejedor", provinciaId: "buenos-aires" },
  { nombre: "Carmen de Areco", provinciaId: "buenos-aires" },
  { nombre: "Chascomús", provinciaId: "buenos-aires" },
  { nombre: "Chivilcoy", provinciaId: "buenos-aires" },
  { nombre: "Colón", provinciaId: "buenos-aires" },
  { nombre: "Coronel Dorrego", provinciaId: "buenos-aires" },
  { nombre: "Coronel Pringles", provinciaId: "buenos-aires" },
  { nombre: "Coronel Rosales", provinciaId: "buenos-aires" },
  { nombre: "Coronel Suárez", provinciaId: "buenos-aires" },
  { nombre: "Daireaux", provinciaId: "buenos-aires" },
  { nombre: "Dolores", provinciaId: "buenos-aires" },
  { nombre: "Ensenada", provinciaId: "buenos-aires" },
  { nombre: "Escobar", provinciaId: "buenos-aires" },
  { nombre: "Esteban Echeverría", provinciaId: "buenos-aires" },
  { nombre: "Exaltación de la Cruz", provinciaId: "buenos-aires" },
  { nombre: "Ezeiza", provinciaId: "buenos-aires" },
  { nombre: "Florencio Varela", provinciaId: "buenos-aires" },
  { nombre: "Florentino Ameghino", provinciaId: "buenos-aires" },
  { nombre: "General Alvarado", provinciaId: "buenos-aires" },
  { nombre: "General Alvear", provinciaId: "buenos-aires" },
  { nombre: "General Arenales", provinciaId: "buenos-aires" },
  { nombre: "General Belgrano", provinciaId: "buenos-aires" },
  { nombre: "General Guido", provinciaId: "buenos-aires" },
  { nombre: "General Juan Madariaga", provinciaId: "buenos-aires" },
  { nombre: "General La Madrid", provinciaId: "buenos-aires" },
  { nombre: "General Las Heras", provinciaId: "buenos-aires" },
  { nombre: "General Lavalle", provinciaId: "buenos-aires" },
  { nombre: "General Paz", provinciaId: "buenos-aires" },
  { nombre: "General Pinto", provinciaId: "buenos-aires" },
  { nombre: "General Pueyrredón", provinciaId: "buenos-aires" },
  { nombre: "General Rodríguez", provinciaId: "buenos-aires" },
  { nombre: "General Salliqueló", provinciaId: "buenos-aires" },
  { nombre: "General San Martín", provinciaId: "buenos-aires" },
  { nombre: "General Viamonte", provinciaId: "buenos-aires" },
  { nombre: "General Villegas", provinciaId: "buenos-aires" },
  { nombre: "Guaminí", provinciaId: "buenos-aires" },
  { nombre: "Hipólito Yrigoyen", provinciaId: "buenos-aires" },
  { nombre: "Hurlingham", provinciaId: "buenos-aires" },
  { nombre: "Ituzaingó", provinciaId: "buenos-aires" },
  { nombre: "José C. Paz", provinciaId: "buenos-aires" },
  { nombre: "Junín", provinciaId: "buenos-aires" },
  { nombre: "La Costa", provinciaId: "buenos-aires" },
  { nombre: "La Matanza", provinciaId: "buenos-aires" },
  { nombre: "La Plata", provinciaId: "buenos-aires" },
  { nombre: "Lanús", provinciaId: "buenos-aires" },
  { nombre: "Laprida", provinciaId: "buenos-aires" },
  { nombre: "Las Flores", provinciaId: "buenos-aires" },
  { nombre: "Leandro N. Alem", provinciaId: "buenos-aires" },
  { nombre: "Lincoln", provinciaId: "buenos-aires" },
  { nombre: "Lobería", provinciaId: "buenos-aires" },
  { nombre: "Lobos", provinciaId: "buenos-aires" },
  { nombre: "Lomas de Zamora", provinciaId: "buenos-aires" },
  { nombre: "Luján", provinciaId: "buenos-aires" },
  { nombre: "Magdalena", provinciaId: "buenos-aires" },
  { nombre: "Maipú", provinciaId: "buenos-aires" },
  { nombre: "Malvinas Argentinas", provinciaId: "buenos-aires" },
  { nombre: "Mar Chiquita", provinciaId: "buenos-aires" },
  { nombre: "Marcos Paz", provinciaId: "buenos-aires" },
  { nombre: "Mercedes", provinciaId: "buenos-aires" },
  { nombre: "Merlo", provinciaId: "buenos-aires" },
  { nombre: "Monte", provinciaId: "buenos-aires" },
  { nombre: "Monte Hermoso", provinciaId: "buenos-aires" },
  { nombre: "Moreno", provinciaId: "buenos-aires" },
  { nombre: "Morón", provinciaId: "buenos-aires" },
  { nombre: "Navarro", provinciaId: "buenos-aires" },
  { nombre: "Necochea", provinciaId: "buenos-aires" },
  { nombre: "Nueve de Julio", provinciaId: "buenos-aires" },
  { nombre: "Olavarría", provinciaId: "buenos-aires" },
  { nombre: "Patagones", provinciaId: "buenos-aires" },
  { nombre: "Pehuajó", provinciaId: "buenos-aires" },
  { nombre: "Pellegrini", provinciaId: "buenos-aires" },
  { nombre: "Pergamino", provinciaId: "buenos-aires" },
  { nombre: "Pila", provinciaId: "buenos-aires" },
  { nombre: "Pilar", provinciaId: "buenos-aires" },
  { nombre: "Pinamar", provinciaId: "buenos-aires" },
  { nombre: "Presidente Perón", provinciaId: "buenos-aires" },
  { nombre: "Puán", provinciaId: "buenos-aires" },
  { nombre: "Punta Indio", provinciaId: "buenos-aires" },
  { nombre: "Quilmes", provinciaId: "buenos-aires" },
  { nombre: "Ramallo", provinciaId: "buenos-aires" },
  { nombre: "Rauch", provinciaId: "buenos-aires" },
  { nombre: "Rivadavia", provinciaId: "buenos-aires" },
  { nombre: "Rojas", provinciaId: "buenos-aires" },
  { nombre: "Roque Pérez", provinciaId: "buenos-aires" },
  { nombre: "Saavedra", provinciaId: "buenos-aires" },
  { nombre: "Saladillo", provinciaId: "buenos-aires" },
  { nombre: "Salliqueló", provinciaId: "buenos-aires" },
  { nombre: "Salto", provinciaId: "buenos-aires" },
  { nombre: "San Andrés de Giles", provinciaId: "buenos-aires" },
  { nombre: "San Antonio de Areco", provinciaId: "buenos-aires" },
  { nombre: "San Cayetano", provinciaId: "buenos-aires" },
  { nombre: "San Fernando", provinciaId: "buenos-aires" },
  { nombre: "San Isidro", provinciaId: "buenos-aires" },
  { nombre: "San Miguel", provinciaId: "buenos-aires" },
  { nombre: "San Nicolás", provinciaId: "buenos-aires" },
  { nombre: "San Pedro", provinciaId: "buenos-aires" },
  { nombre: "San Vicente", provinciaId: "buenos-aires" },
  { nombre: "Suipacha", provinciaId: "buenos-aires" },
  { nombre: "Tandil", provinciaId: "buenos-aires" },
  { nombre: "Tapalqué", provinciaId: "buenos-aires" },
  { nombre: "Tigre", provinciaId: "buenos-aires" },
  { nombre: "Tordillo", provinciaId: "buenos-aires" },
  { nombre: "Tornquist", provinciaId: "buenos-aires" },
  { nombre: "Trenque Lauquen", provinciaId: "buenos-aires" },
  { nombre: "Tres Arroyos", provinciaId: "buenos-aires" },
  { nombre: "Tres de Febrero", provinciaId: "buenos-aires" },
  { nombre: "Tres Lomas", provinciaId: "buenos-aires" },
  { nombre: "Veinticinco de Mayo", provinciaId: "buenos-aires" },
  { nombre: "Vicente López", provinciaId: "buenos-aires" },
  { nombre: "Villarino", provinciaId: "buenos-aires" },
  { nombre: "Zárate", provinciaId: "buenos-aires" },

  // ─── Catamarca ───
  { nombre: "Ambato", provinciaId: "catamarca" },
  { nombre: "Ancasti", provinciaId: "catamarca" },
  { nombre: "Andalgalá", provinciaId: "catamarca" },
  { nombre: "Antofagasta de la Sierra", provinciaId: "catamarca" },
  { nombre: "Belén", provinciaId: "catamarca" },
  { nombre: "Capayán", provinciaId: "catamarca" },
  { nombre: "El Alto", provinciaId: "catamarca" },
  { nombre: "Fray Mamerto Esquiú", provinciaId: "catamarca" },
  { nombre: "La Paz", provinciaId: "catamarca" },
  { nombre: "Paclín", provinciaId: "catamarca" },
  { nombre: "Pomán", provinciaId: "catamarca" },
  { nombre: "San Fernando del Valle de Catamarca", provinciaId: "catamarca" },
  { nombre: "Santa María", provinciaId: "catamarca" },
  { nombre: "Santa Rosa", provinciaId: "catamarca" },
  { nombre: "Tinogasta", provinciaId: "catamarca" },
  { nombre: "Valle Viejo", provinciaId: "catamarca" },

  // ─── Chaco ───
  { nombre: "Almirante Brown", provinciaId: "chaco" },
  { nombre: "Chacabuco", provinciaId: "chaco" },
  { nombre: "Comandante Fernández", provinciaId: "chaco" },
  { nombre: "Doce de Octubre", provinciaId: "chaco" },
  { nombre: "Dos de Abril", provinciaId: "chaco" },
  { nombre: "Fray Justo Santa María de Oro", provinciaId: "chaco" },
  { nombre: "General Belgrano", provinciaId: "chaco" },
  { nombre: "General Donovan", provinciaId: "chaco" },
  { nombre: "General Güemes", provinciaId: "chaco" },
  { nombre: "Independencia", provinciaId: "chaco" },
  { nombre: "Libertad", provinciaId: "chaco" },
  { nombre: "Libertador General San Martín", provinciaId: "chaco" },
  { nombre: "Maipú", provinciaId: "chaco" },
  { nombre: "Mayor Luis J. Fontana", provinciaId: "chaco" },
  { nombre: "Nueve de Julio", provinciaId: "chaco" },
  { nombre: "O'Higgins", provinciaId: "chaco" },
  { nombre: "Presidencia de la Plaza", provinciaId: "chaco" },
  { nombre: "Quitilipi", provinciaId: "chaco" },
  { nombre: "Resistencia", provinciaId: "chaco" },
  { nombre: "San Lorenzo", provinciaId: "chaco" },
  { nombre: "Sargento Cabral", provinciaId: "chaco" },
  { nombre: "Tapenagá", provinciaId: "chaco" },
  { nombre: "Veinticinco de Mayo", provinciaId: "chaco" },

  // ─── Chubut ───
  { nombre: "Comodoro Rivadavia", provinciaId: "chubut" },
  { nombre: "Esquel", provinciaId: "chubut" },
  { nombre: "Gaiman", provinciaId: "chubut" },
  { nombre: "Puerto Madryn", provinciaId: "chubut" },
  { nombre: "Rawson", provinciaId: "chubut" },
  { nombre: "Río Senguer", provinciaId: "chubut" },
  { nombre: "Sarmiento", provinciaId: "chubut" },
  { nombre: "Trelew", provinciaId: "chubut" },

  // ─── Córdoba ───
  { nombre: "Alta Gracia", provinciaId: "cordoba" },
  { nombre: "Bell Ville", provinciaId: "cordoba" },
  { nombre: "Córdoba", provinciaId: "cordoba" },
  { nombre: "Cruz del Eje", provinciaId: "cordoba" },
  { nombre: "Dean Funes", provinciaId: "cordoba" },
  { nombre: "Jesús María", provinciaId: "cordoba" },
  { nombre: "La Falda", provinciaId: "cordoba" },
  { nombre: "Marcos Juárez", provinciaId: "cordoba" },
  { nombre: "Río Cuarto", provinciaId: "cordoba" },
  { nombre: "Río Tercero", provinciaId: "cordoba" },
  { nombre: "San Francisco", provinciaId: "cordoba" },
  { nombre: "Villa Carlos Paz", provinciaId: "cordoba" },
  { nombre: "Villa Dolores", provinciaId: "cordoba" },
  { nombre: "Villa María", provinciaId: "cordoba" },
  { nombre: "Villa Nueva", provinciaId: "cordoba" },

  // ─── Corrientes ───
  { nombre: "Bella Vista", provinciaId: "corrientes" },
  { nombre: "Corrientes", provinciaId: "corrientes" },
  { nombre: "Curuzú Cuatiá", provinciaId: "corrientes" },
  { nombre: "Goya", provinciaId: "corrientes" },
  { nombre: "Ituzaingó", provinciaId: "corrientes" },
  { nombre: "Mercedes", provinciaId: "corrientes" },
  { nombre: "Monte Caseros", provinciaId: "corrientes" },
  { nombre: "Paso de los Libres", provinciaId: "corrientes" },
  { nombre: "Santo Tomé", provinciaId: "corrientes" },

  // ─── Entre Ríos ───
  { nombre: "Colón", provinciaId: "entre-rios" },
  { nombre: "Concordia", provinciaId: "entre-rios" },
  { nombre: "Concepción del Uruguay", provinciaId: "entre-rios" },
  { nombre: "Gualeguay", provinciaId: "entre-rios" },
  { nombre: "Gualeguaychú", provinciaId: "entre-rios" },
  { nombre: "La Paz", provinciaId: "entre-rios" },
  { nombre: "Nogoyá", provinciaId: "entre-rios" },
  { nombre: "Paraná", provinciaId: "entre-rios" },
  { nombre: "Victoria", provinciaId: "entre-rios" },
  { nombre: "Villaguay", provinciaId: "entre-rios" },

  // ─── Formosa ───
  { nombre: "Clorinda", provinciaId: "formosa" },
  { nombre: "Formosa", provinciaId: "formosa" },
  { nombre: "Ingeniero Juárez", provinciaId: "formosa" },
  { nombre: "Pirané", provinciaId: "formosa" },

  // ─── Jujuy ───
  { nombre: "El Carmen", provinciaId: "jujuy" },
  { nombre: "Humahuaca", provinciaId: "jujuy" },
  { nombre: "Ledesma", provinciaId: "jujuy" },
  { nombre: "Libertador General San Martín", provinciaId: "jujuy" },
  { nombre: "Palpalá", provinciaId: "jujuy" },
  { nombre: "San Pedro de Jujuy", provinciaId: "jujuy" },
  { nombre: "San Salvador de Jujuy", provinciaId: "jujuy" },
  { nombre: "Tilcara", provinciaId: "jujuy" },

  // ─── La Pampa ───
  { nombre: "General Acha", provinciaId: "la-pampa" },
  { nombre: "General Pico", provinciaId: "la-pampa" },
  { nombre: "Realicó", provinciaId: "la-pampa" },
  { nombre: "Santa Rosa", provinciaId: "la-pampa" },
  { nombre: "Toay", provinciaId: "la-pampa" },

  // ─── La Rioja ───
  { nombre: "Chilecito", provinciaId: "la-rioja" },
  { nombre: "La Rioja", provinciaId: "la-rioja" },
  { nombre: "Chamical", provinciaId: "la-rioja" },
  { nombre: "Aimogasta", provinciaId: "la-rioja" },

  // ─── Mendoza ───
  { nombre: "General Alvear", provinciaId: "mendoza" },
  { nombre: "Godoy Cruz", provinciaId: "mendoza" },
  { nombre: "Guaymallén", provinciaId: "mendoza" },
  { nombre: "Junín", provinciaId: "mendoza" },
  { nombre: "Las Heras", provinciaId: "mendoza" },
  { nombre: "Lavalle", provinciaId: "mendoza" },
  { nombre: "Luján de Cuyo", provinciaId: "mendoza" },
  { nombre: "Maipú", provinciaId: "mendoza" },
  { nombre: "Malargüe", provinciaId: "mendoza" },
  { nombre: "Mendoza", provinciaId: "mendoza" },
  { nombre: "Rivadavia", provinciaId: "mendoza" },
  { nombre: "San Carlos", provinciaId: "mendoza" },
  { nombre: "San Martín", provinciaId: "mendoza" },
  { nombre: "San Rafael", provinciaId: "mendoza" },
  { nombre: "Santa Rosa", provinciaId: "mendoza" },
  { nombre: "Tunuyán", provinciaId: "mendoza" },
  { nombre: "Tupungato", provinciaId: "mendoza" },

  // ─── Misiones ───
  { nombre: "Apóstoles", provinciaId: "misiones" },
  { nombre: "Eldorado", provinciaId: "misiones" },
  { nombre: "Oberá", provinciaId: "misiones" },
  { nombre: "Posadas", provinciaId: "misiones" },
  { nombre: "Puerto Iguazú", provinciaId: "misiones" },

  // ─── Neuquén ───
  { nombre: "Chos Malal", provinciaId: "neuquen" },
  { nombre: "Cutral Có", provinciaId: "neuquen" },
  { nombre: "Junín de los Andes", provinciaId: "neuquen" },
  { nombre: "Neuquén", provinciaId: "neuquen" },
  { nombre: "San Martín de los Andes", provinciaId: "neuquen" },
  { nombre: "Villa La Angostura", provinciaId: "neuquen" },
  { nombre: "Zapala", provinciaId: "neuquen" },

  // ─── Río Negro ───
  { nombre: "Bariloche", provinciaId: "rio-negro" },
  { nombre: "Catriel", provinciaId: "rio-negro" },
  { nombre: "Cipolletti", provinciaId: "rio-negro" },
  { nombre: "El Bolsón", provinciaId: "rio-negro" },
  { nombre: "General Roca", provinciaId: "rio-negro" },
  { nombre: "San Antonio Oeste", provinciaId: "rio-negro" },
  { nombre: "Viedma", provinciaId: "rio-negro" },
  { nombre: "Villa Regina", provinciaId: "rio-negro" },

  // ─── Salta ───
  { nombre: "Cafayate", provinciaId: "salta" },
  { nombre: "Cachi", provinciaId: "salta" },
  { nombre: "General Güemes", provinciaId: "salta" },
  { nombre: "Metán", provinciaId: "salta" },
  { nombre: "Orán", provinciaId: "salta" },
  { nombre: "Rosario de la Frontera", provinciaId: "salta" },
  { nombre: "Salta", provinciaId: "salta" },
  { nombre: "Tartagal", provinciaId: "salta" },

  // ─── San Juan ───
  { nombre: "Caucete", provinciaId: "san-juan" },
  { nombre: "Chimbas", provinciaId: "san-juan" },
  { nombre: "Rawson", provinciaId: "san-juan" },
  { nombre: "Rivadavia", provinciaId: "san-juan" },
  { nombre: "San Juan", provinciaId: "san-juan" },
  { nombre: "Santa Lucía", provinciaId: "san-juan" },
  { nombre: "Pocito", provinciaId: "san-juan" },

  // ─── San Luis ───
  { nombre: "Merlo", provinciaId: "san-luis" },
  { nombre: "San Luis", provinciaId: "san-luis" },
  { nombre: "Villa Mercedes", provinciaId: "san-luis" },

  // ─── Santa Cruz ───
  { nombre: "Caleta Olivia", provinciaId: "santa-cruz" },
  { nombre: "El Calafate", provinciaId: "santa-cruz" },
  { nombre: "Puerto Deseado", provinciaId: "santa-cruz" },
  { nombre: "Río Gallegos", provinciaId: "santa-cruz" },
  { nombre: "Río Turbio", provinciaId: "santa-cruz" },

  // ─── Santa Fe ───
  { nombre: "Rafaela", provinciaId: "santa-fe" },
  { nombre: "Reconquista", provinciaId: "santa-fe" },
  { nombre: "Rosario", provinciaId: "santa-fe" },
  { nombre: "Santa Fe", provinciaId: "santa-fe" },
  { nombre: "Santo Tomé", provinciaId: "santa-fe" },
  { nombre: "Venado Tuerto", provinciaId: "santa-fe" },
  { nombre: "Villa Constitución", provinciaId: "santa-fe" },

  // ─── Santiago del Estero ───
  { nombre: "Frías", provinciaId: "santiago-del-estero" },
  { nombre: "La Banda", provinciaId: "santiago-del-estero" },
  { nombre: "Loreto", provinciaId: "santiago-del-estero" },
  { nombre: "Añatuya", provinciaId: "santiago-del-estero" },
  { nombre: "Santiago del Estero", provinciaId: "santiago-del-estero" },
  { nombre: "Termas de Río Hondo", provinciaId: "santiago-del-estero" },

  // ─── Tierra del Fuego ───
  { nombre: "Río Grande", provinciaId: "tierra-del-fuego" },
  { nombre: "Tolhuin", provinciaId: "tierra-del-fuego" },
  { nombre: "Ushuaia", provinciaId: "tierra-del-fuego" },

  // ─── Tucumán ───
  { nombre: "Aguilares", provinciaId: "tucuman" },
  { nombre: "Banda del Río Salí", provinciaId: "tucuman" },
  { nombre: "Concepción", provinciaId: "tucuman" },
  { nombre: "Famaillá", provinciaId: "tucuman" },
  { nombre: "Monteros", provinciaId: "tucuman" },
  { nombre: "San Miguel de Tucumán", provinciaId: "tucuman" },
  { nombre: "Tafí Viejo", provinciaId: "tucuman" },
  { nombre: "Yerba Buena", provinciaId: "tucuman" },
];

// Retorna los municipios de una provincia ordenados alfabéticamente.
export function getMunicipiosByProvincia(provinciaId: string): string[] {
  return MUNICIPIOS.filter((m) => m.provinciaId === provinciaId)
    .map((m) => m.nombre)
    .sort((a, b) => a.localeCompare(b, "es"));
}
