create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  role text not null check (role in ('profesor', 'alumno')),
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Usuarios pueden leer su perfil" on public.profiles;
create policy "Usuarios pueden leer su perfil"
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Usuarios pueden actualizar su perfil" on public.profiles;
create policy "Usuarios pueden actualizar su perfil"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_role text;
  selected_name text;
begin
  selected_role := coalesce(new.raw_user_meta_data ->> 'role', 'alumno');

  if selected_role not in ('profesor', 'alumno') then
    selected_role := 'alumno';
  end if;

  selected_name := nullif(trim(coalesce(new.raw_user_meta_data ->> 'name', '')), '');

  if selected_name is null then
    selected_name := split_part(new.email, '@', 1);
  end if;

  insert into public.profiles (user_id, role, name)
  values (new.id, selected_role, selected_name);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();
