create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  profesor_id uuid not null references auth.users(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  slot_duration_minutes integer not null check (slot_duration_minutes > 0),
  created_at timestamptz not null default now(),
  check (start_time < end_time)
);

create unique index if not exists availability_unique_slot_idx
  on public.availability (profesor_id, day_of_week, start_time, end_time);

create table if not exists public.blocked_dates (
  id bigint generated by default as identity primary key,
  profesor_id uuid not null references auth.users(id) on delete cascade,
  blocked_date date not null,
  reason text,
  created_at timestamptz not null default now()
);

create unique index if not exists blocked_dates_unique_idx
  on public.blocked_dates (profesor_id, blocked_date);

alter table public.availability enable row level security;
alter table public.blocked_dates enable row level security;

drop policy if exists "Users can read own availability" on public.availability;
create policy "Users can read own availability"
  on public.availability
  for select
  to authenticated
  using (auth.uid() = profesor_id);

drop policy if exists "Users can insert own availability" on public.availability;
create policy "Users can insert own availability"
  on public.availability
  for insert
  to authenticated
  with check (auth.uid() = profesor_id);

drop policy if exists "Users can update own availability" on public.availability;
create policy "Users can update own availability"
  on public.availability
  for update
  to authenticated
  using (auth.uid() = profesor_id)
  with check (auth.uid() = profesor_id);

drop policy if exists "Users can delete own availability" on public.availability;
create policy "Users can delete own availability"
  on public.availability
  for delete
  to authenticated
  using (auth.uid() = profesor_id);

drop policy if exists "Users can read own blocked dates" on public.blocked_dates;
create policy "Users can read own blocked dates"
  on public.blocked_dates
  for select
  to authenticated
  using (auth.uid() = profesor_id);

drop policy if exists "Users can insert own blocked dates" on public.blocked_dates;
create policy "Users can insert own blocked dates"
  on public.blocked_dates
  for insert
  to authenticated
  with check (auth.uid() = profesor_id);

drop policy if exists "Users can update own blocked dates" on public.blocked_dates;
create policy "Users can update own blocked dates"
  on public.blocked_dates
  for update
  to authenticated
  using (auth.uid() = profesor_id)
  with check (auth.uid() = profesor_id);

drop policy if exists "Users can delete own blocked dates" on public.blocked_dates;
create policy "Users can delete own blocked dates"
  on public.blocked_dates
  for delete
  to authenticated
  using (auth.uid() = profesor_id);
