create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  profesor_id uuid not null references auth.users(id) on delete cascade,
  alumno_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  start_time time not null,
  end_time time not null,
  status text not null default 'pendiente'
    check (status in ('pendiente', 'confirmado', 'cancelado')),
  created_at timestamptz not null default now(),
  check (start_time < end_time)
);

drop index if exists bookings_unique_slot_idx;
create unique index if not exists bookings_unique_active_slot_idx
  on public.bookings (profesor_id, date, start_time, end_time)
  where status in ('pendiente', 'confirmado');

create index if not exists bookings_profesor_status_idx
  on public.bookings (profesor_id, status, date);

create index if not exists bookings_alumno_idx
  on public.bookings (alumno_id, created_at desc);

alter table public.bookings enable row level security;

drop policy if exists "Alumnos pueden ver sus bookings" on public.bookings;
create policy "Alumnos pueden ver sus bookings"
  on public.bookings
  for select
  to authenticated
  using (auth.uid() = alumno_id);

drop policy if exists "Alumnos pueden crear sus bookings" on public.bookings;
create policy "Alumnos pueden crear sus bookings"
  on public.bookings
  for insert
  to authenticated
  with check (auth.uid() = alumno_id);

drop policy if exists "Profesores pueden ver bookings recibidos" on public.bookings;
create policy "Profesores pueden ver bookings recibidos"
  on public.bookings
  for select
  to authenticated
  using (auth.uid() = profesor_id);
