create table if not exists public.booking_solo_decisions (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  profesor_id uuid not null references auth.users(id) on delete cascade,
  alumno_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pendiente'
    check (status in ('pendiente', 'aceptada_individual', 'cancelada_alumno')),
  decision_deadline_at timestamptz,
  created_at timestamptz not null default now(),
  responded_at timestamptz
);

create unique index if not exists booking_solo_decisions_unique_pending_idx
  on public.booking_solo_decisions (booking_id)
  where status = 'pendiente';

create index if not exists booking_solo_decisions_alumno_status_idx
  on public.booking_solo_decisions (alumno_id, status, created_at desc);

create index if not exists booking_solo_decisions_profesor_status_idx
  on public.booking_solo_decisions (profesor_id, status, created_at desc);

alter table public.booking_solo_decisions enable row level security;

drop policy if exists "Profesor puede crear decision solo" on public.booking_solo_decisions;
create policy "Profesor puede crear decision solo"
  on public.booking_solo_decisions
  for insert
  to authenticated
  with check (auth.uid() = profesor_id and status = 'pendiente');

drop policy if exists "Alumno puede ver sus decisiones solo" on public.booking_solo_decisions;
create policy "Alumno puede ver sus decisiones solo"
  on public.booking_solo_decisions
  for select
  to authenticated
  using (auth.uid() = alumno_id);

drop policy if exists "Alumno puede responder decision a aceptada_individual" on public.booking_solo_decisions;
create policy "Alumno puede responder decision a aceptada_individual"
  on public.booking_solo_decisions
  for update
  to authenticated
  using (auth.uid() = alumno_id and status = 'pendiente')
  with check (
    auth.uid() = alumno_id
    and status = 'aceptada_individual'
    and responded_at is not null
  );

drop policy if exists "Alumno puede responder decision a cancelada_alumno" on public.booking_solo_decisions;
create policy "Alumno puede responder decision a cancelada_alumno"
  on public.booking_solo_decisions
  for update
  to authenticated
  using (auth.uid() = alumno_id and status = 'pendiente')
  with check (
    auth.uid() = alumno_id
    and status = 'cancelada_alumno'
    and responded_at is not null
  );

drop policy if exists "Profesor puede ver decisiones emitidas" on public.booking_solo_decisions;
create policy "Profesor puede ver decisiones emitidas"
  on public.booking_solo_decisions
  for select
  to authenticated
  using (auth.uid() = profesor_id);
