create table if not exists public.profesor_alumno_notes (
  id bigint generated by default as identity primary key,
  profesor_id uuid not null references auth.users(id) on delete cascade,
  alumno_id uuid not null references auth.users(id) on delete cascade,
  note text not null default '',
  updated_at timestamptz not null default now(),
  unique (profesor_id, alumno_id)
);

create index if not exists profesor_alumno_notes_profesor_idx
  on public.profesor_alumno_notes (profesor_id, alumno_id);

alter table public.profesor_alumno_notes enable row level security;

drop policy if exists "Profesor puede ver sus notas privadas por alumno" on public.profesor_alumno_notes;
create policy "Profesor puede ver sus notas privadas por alumno"
  on public.profesor_alumno_notes
  for select
  to authenticated
  using (profesor_id = auth.uid());

drop policy if exists "Profesor puede crear sus notas privadas por alumno" on public.profesor_alumno_notes;
create policy "Profesor puede crear sus notas privadas por alumno"
  on public.profesor_alumno_notes
  for insert
  to authenticated
  with check (profesor_id = auth.uid());

drop policy if exists "Profesor puede editar sus notas privadas por alumno" on public.profesor_alumno_notes;
create policy "Profesor puede editar sus notas privadas por alumno"
  on public.profesor_alumno_notes
  for update
  to authenticated
  using (profesor_id = auth.uid())
  with check (profesor_id = auth.uid());
